### PR TITLE
Fixes - Modification - Events

### PR DESCRIPTION
**Pull request by fmido88**
1- Add some fixes to the code.
2- Adding an option to the method of overriding.
3- Adding events for overriding.

(re-open the pull to be able to merge)

### CODE REVIEW

**Comment by fmido88** [comment]
Is the last changes okay?

**Comment by danielneis** [comment]
Hello,
I'm busy this week, I'll review everything next week.

**Comment by fmido88** [comment]
Hey Daniel
Take your time

**Comment by fmido88** [comment]
Last change I added a capability for overriding, so only users with this capability can override maxviews.
Because may be the admin want to grant it to users which not having capability to mange activities or otherwise grant capability to roles to mange activity but not overriding.

**Pull request closed without merging**
